version: "3.9"

services:
  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile.prod
    volumes:
      - ./client:/var/www
    ports:
      - 4444:4444
    depends_on:
      - nginx
    networks:
      survey-factory_net:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    volumes:
      - php_socket:/var/run/php-fpm
      - ./api/src/:/api/src
    depends_on:
      - db
    networks:
      survey-factory_net:

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 8080:80
    depends_on:
      - api
    volumes:
      - php_socket:/var/run/php-fpm
      - ./api/src/:/api/src
    networks:
      survey-factory_net:

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    # platform: linux/amd64 # M1チップの場合はコメントアウトを外す
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: surveyfactory
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - type: bind
        source: ./docker/db/sql
        target: /docker-entrypoint-initdb.d
      - type: bind
        source: ./docker/db/my.conf
        target: /etc/mysql/conf.d/my.conf
      - mysql-volume:/var/lib/mysql
    networks:
      survey-factory_net:

volumes:
  php_socket:
  mysql-volume:

networks:
  survey-factory_net:
    external: true